#!/bin/bash
#SBATCH --time=43:00:00
#SBATCH --mem=120gb
#SBATCH --ntasks-per-node=6
#SBATCH --cpus-per-task=4     


module load picard/2.25.5
module load amazon-corretto/16.0.0.36.1
module load igvtools/2.11.3
module load bowtie/2.4.4
module load fastqc/0.11.9
module load trimgalore/0.6.6
module load sratoolkit/3.0.2
module load samtools/1.16.1
module load bismark/0.23.0
module load R/4.0.5
module load bedtools/2.30.0
module load python/3.9.4
module load parallel/20210322
module load methyldackel/0.6.1
module load bismark/0.23.0



cd ${SLURM_SUBMIT_DIR}


#Majel
python /datasets/work/hb-meth-atlas/work/pipeline_data/majel_wgbspipline/main_old/Majel_petrichor.py  --data_dir /scratch3/ma032/WGBS//fastq/  --is_paired_end True --threads 24 --genome hg38  --sample_name Skin_QUT229  -v 3 --log_file Skin_QUT229.log &> Log_file_2.txt
bash /datasets/work/hb-meth-atlas/work/pipeline_data/majel_wgbspipline/main_old/majel_cleanup_2025.sh Skin_QUT229






